version: "3.8"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - mynet
    restart: always
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - ./.next:./app/.next
    command: npm run dev

networks:
  mynet:
