export const AppContent = {
	brandname: "frontendweb",
	privacyPolicy: "Privacy policy",
	termAndConditions: "Term and conditions",
	poweredBy: "powered by",
	reserved: "All rights reserved",
	liked: "You have already liked the post!",
	dislike: "You have already dis-liked the post!",
	saveText: "Save",
	updateText: "Update",
	deleteText: "Delete",
	signIn: "Sign In",
	signUp: "Sign Up",
	signUpHere: "sign up here",
	signInHere: "sign in here",
	signupText: "Don't have an account? click here to",
	signInText: "Already have an account?",
	createPost: "Create Post",
	publish: "Publish",
	fileUploadDragText: "Drag files to upload",
	browse: "Browse",
	or: "Or",
	forgotPassword: "Forgot password",
	resetPassword: "Reset password",
	forgotPasswordText: "FORGOT<br />Your password?",
	notToWorryText: "Not to worry, we got you! Let's get you a new password.",
	resetNotRequestText:
		"If you didn't request a password reset, you can ignore this email. Your password will not be changed.",
	needMoreHelp: "Need more help?",
};
